chore: ansible and bashrc enhancements

diff --git a/home/private_readonly_dot_bashrc.tmpl b/home/private_readonly_dot_bashrc.tmpl
--- a/home/private_readonly_dot_bashrc.tmpl
+++ b/home/private_readonly_dot_bashrc.tmpl
@@ -48,10 +48,6 @@ tabs -4
 
 {@'- /* {{{ Template variables definition */'@}
 
-{@'- /* These escape-sequences are only needed for PS1 */'@}
-{@'- $escStart := `\[` '@}
-{@'- $escEnd := `\]` '@}
-
 {@'- /* Terminal color codes */'@}
 {@'- /* See: https://misc.flogisoft.com/bash/tip_colors_and_formatting */'@}
 {@'- $coloRed := `\033[01;31m` '@}
@@ -63,30 +59,19 @@ tabs -4
 {@'- $coloWhite := `\033[01;37m` '@}
 {@'- $coloDefault := `\033[00m` '@}
 
-{@'- /* Terminal color codes to be used in PS1 */'@}
-{@'- $colourGreen := print $escStart $coloGreen $escEnd '@}
-{@'- $colourYellow := print $escStart $coloYellow $escEnd '@}
-{@'- $colourBlue := print $escStart $coloBlue $escEnd '@}
-{@'- $colourMagenta := print $escStart $coloMagenta $escEnd '@}
-{@'- $colourCyan := print $escStart $coloCyan $escEnd '@}
-{@'- $colourWhite := print $escStart $coloWhite $escEnd '@}
-{@'- $colourDefault := print $escStart $coloDefault $escEnd '@}
-
-{@'- /* These color codes (without $escStart and $escEnd) are used in our function in printf */'@}
+{@'- /* These color codes are used in our function in printf */'@}
 {@'- $lineColo := $coloGreen '@}
 {@'- $bracketColo := $coloGreen '@}
 {@'- $branchCleanColo := $coloBlue '@}
 {@'- $branchDirtyColo := $coloRed '@}
-
-{@'- /* These color codes (with $escStart and $escEnd) are used in PS1 directly */'@}
-{@'- $lineColour := print $escStart $lineColo $escEnd '@}
-{@'- $bracketColour := print $escStart $bracketColo $escEnd '@}
-{@'- $clockColour := $colourBlue '@}
-{@'- $jobColour := $colourBlue '@}
-{@'- $pathColour := $colourBlue '@}
-{@'- $distroColour := $colourCyan '@}
-{@'- $usernameColour := $colourCyan '@}
-{@'- $endCharacterColour := $colourGreen '@}
+{@'- $distroColo := $coloCyan '@}
+{@'- $exitCodeOk := $coloBlue '@}
+{@'- $exitCodeBad := $coloRed '@}
+{@'- $usernameColo := $coloCyan '@}
+{@'- $clockColo := $coloBlue '@}
+{@'- $pathColo := $coloBlue '@}
+{@'- $usernameColo := $coloCyan '@}
+{@'- $endCharacterColo := $coloGreen '@}
 
 {@'- /* Box characters to be used in the prompt */'@}
 {@'- $lineBottomCorner := `\342\224\224` '@}
@@ -100,7 +85,7 @@ tabs -4
 {@'- /* }}} */'@}
 
 # If inside a git working tree, print current git branch in the bottom line of the command prompt
-function print_git_branch() {
+function VBD_PrintGitBranch() {
 	if git rev-parse --is-inside-work-tree 1>/dev/null 2>&1 ; then 
 		local branch_colo
 		# Check if there are changes in the local repo and choose color of the branch name accordingly
@@ -116,12 +101,34 @@ function print_git_branch() {
 	fi
 }
 
-PS1={@' print $lineColour $lineUpperCorner $lineStraight $lineStraight $bracketColour "[" $distroColour .chezmoi.osRelease.id $bracketColour "]" $lineColour $lineStraight $bracketColour "[" $usernameColour `\u@\h ` $pathColour `\w` $bracketColour "]" $colourDefault `\n` $lineColour $lineBottomCorner $lineStraight $lineStraight "$(print_git_branch)" $bracketColour "[" $jobColour `\j` $bracketColour "]" $lineColour $lineStraight $bracketColour "[" $clockColour `\t` $bracketColour "]" $lineColour $lineStraight $endCharacterColour $endCharacter $escStart "$(tput sgr0)" $escEnd " " | squote '@}
+# Print exit code. This function should be called from inside brackets 
+function VBD_PrintExitCode() {
+	local exit_code=$?
+	if [[ $exit_code -eq 0 ]] ; then
+		printf {@' print $exitCodeOk "0" | squote '@}
+	else
+		printf {@' print $exitCodeBad "%i" | squote '@} $exit_code
+	fi
+}
 
-{@' if false -'@}
-# Old variant of PS1 used to be used in Void Linux
-#PS1='\[\e[01;32m\][\u@\h \[\e[01;34m\]\w\[\e[01;32m\]]\$\[\e[00m\] '
-{@'- end -'@}
+if [[ $TERM == 'linux' ]] ; then
+	distro_logo={@' .chezmoi.osRelease.id | squote '@}
+else
+	distro_logo={@' includeTemplate "distro-logo.tmpl" . | squote '@}
+fi
+
+PS1={@' print
+	$lineColo $lineUpperCorner $lineStraight $lineStraight
+	$bracketColo "(" $distroColo `'"$distro_logo"'` $bracketColo ")" $lineColo $lineStraight
+	$bracketColo "[" $usernameColo `\u@\h ` $pathColo `\w` $bracketColo "]" $coloDefault `\n`
+	$lineColo $lineBottomCorner $lineStraight $lineStraight
+	$bracketColo "(" "$(VBD_PrintExitCode)" $bracketColo ")" $lineColo $lineStraight "$(VBD_PrintGitBranch)"
+	$bracketColo "[" $clockColo `\t` $bracketColo "]" $lineColo $lineStraight
+	$endCharacterColo $endCharacter "$(tput sgr0)" " "
+	| squote
+'@}
+
+unset distro_logo
 
 # If this is a graphical terminal, then set the window title to 'user@host: dir'
 # The list of conditions is borrowed from Gentoo's global bash config
